version: '3.7'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_VERSION: "1.0.0"
        GIT_REVISION: "local"
        OCI_DESCRIPTION: "Campfire - Self-hosted chat application"
        OCI_SOURCE: "https://github.com/mauricewipf/campfire-umbrel"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./local-data/storage:/rails/storage
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      REDIS_URL: redis://redis:6379
      DISABLE_SSL: 'true'
      VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY:-}
      VAPID_PRIVATE_KEY: ${VAPID_PRIVATE_KEY:-}
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - ./local-data/redis:/data
    restart: unless-stopped
