version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: campfire_server_1
      APP_PORT: 80
      PROXY_AUTH_ADD: 'false'
    container_name: campfire_app_proxy_1

  server:
    image: campfire:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_VERSION: ${APP_VERSION:-1.0.0}
        GIT_REVISION: ${GIT_REVISION:-unknown}
        OCI_DESCRIPTION: "Campfire - Self-hosted chat application"
        OCI_SOURCE: "https://github.com/mauricewipf/campfire-umbrel"
    volumes:
      - ${APP_DATA_DIR}/data/storage:/rails/storage
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: ${APP_SEED}
      REDIS_URL: redis://campfire_redis_1:6379
      DISABLE_SSL: 'true'
      VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY:-}
      VAPID_PRIVATE_KEY: ${VAPID_PRIVATE_KEY:-}
      SENTRY_DSN: ${SENTRY_DSN:-}
    depends_on:
      - redis
    restart: on-failure
    container_name: campfire_server_1

  redis:
    image: redis:7-alpine
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - ${APP_DATA_DIR}/data/redis:/data
    restart: on-failure
    container_name: campfire_redis_1
