#!/usr/bin/env ruby
require "bundler/setup"
require "securerandom"
require "web_push"

vapid_key = WebPush.generate_key

puts "SECRET_KEY_BASE=#{SecureRandom.hex(64)}"
puts "CAMPFIRE_FIRST_RUN_TOKEN=#{SecureRandom.urlsafe_base64(32)}"
puts "VAPID_PRIVATE_KEY=#{vapid_key.private_key}"
puts "VAPID_PUBLIC_KEY=#{vapid_key.public_key}"
